// Code generated by ent, DO NOT EDIT.

package videojob

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the videojob type in the database.
	Label = "video_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldUpstreamJobID holds the string denoting the upstream_job_id field in the database.
	FieldUpstreamJobID = "upstream_job_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRequestedModel holds the string denoting the requested_model field in the database.
	FieldRequestedModel = "requested_model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldPrompt holds the string denoting the prompt field in the database.
	FieldPrompt = "prompt"
	// FieldResolution holds the string denoting the resolution field in the database.
	FieldResolution = "resolution"
	// FieldDurationSeconds holds the string denoting the duration_seconds field in the database.
	FieldDurationSeconds = "duration_seconds"
	// FieldAspectRatio holds the string denoting the aspect_ratio field in the database.
	FieldAspectRatio = "aspect_ratio"
	// FieldAudio holds the string denoting the audio field in the database.
	FieldAudio = "audio"
	// FieldImageSource holds the string denoting the image_source field in the database.
	FieldImageSource = "image_source"
	// FieldImageURL holds the string denoting the image_url field in the database.
	FieldImageURL = "image_url"
	// FieldLocalInputName holds the string denoting the local_input_name field in the database.
	FieldLocalInputName = "local_input_name"
	// FieldResult holds the string denoting the result field in the database.
	FieldResult = "result"
	// FieldErrorMessage holds the string denoting the error_message field in the database.
	FieldErrorMessage = "error_message"
	// FieldHoldAmount holds the string denoting the hold_amount field in the database.
	FieldHoldAmount = "hold_amount"
	// FieldActualCost holds the string denoting the actual_cost field in the database.
	FieldActualCost = "actual_cost"
	// FieldBillingSnapshot holds the string denoting the billing_snapshot field in the database.
	FieldBillingSnapshot = "billing_snapshot"
	// FieldRequestHash holds the string denoting the request_hash field in the database.
	FieldRequestHash = "request_hash"
	// FieldSettledAt holds the string denoting the settled_at field in the database.
	FieldSettledAt = "settled_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// Table holds the table name of the videojob in the database.
	Table = "video_jobs"
)

// Columns holds all SQL columns for videojob fields.
var Columns = []string{
	FieldID,
	FieldJobID,
	FieldUserID,
	FieldAPIKeyID,
	FieldGroupID,
	FieldAccountID,
	FieldUpstreamJobID,
	FieldStatus,
	FieldRequestedModel,
	FieldUpstreamModel,
	FieldPrompt,
	FieldResolution,
	FieldDurationSeconds,
	FieldAspectRatio,
	FieldAudio,
	FieldImageSource,
	FieldImageURL,
	FieldLocalInputName,
	FieldResult,
	FieldErrorMessage,
	FieldHoldAmount,
	FieldActualCost,
	FieldBillingSnapshot,
	FieldRequestHash,
	FieldSettledAt,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldStartedAt,
	FieldFinishedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// JobIDValidator is a validator for the "job_id" field. It is called by the builders before save.
	JobIDValidator func(string) error
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// RequestedModelValidator is a validator for the "requested_model" field. It is called by the builders before save.
	RequestedModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// ResolutionValidator is a validator for the "resolution" field. It is called by the builders before save.
	ResolutionValidator func(string) error
	// AspectRatioValidator is a validator for the "aspect_ratio" field. It is called by the builders before save.
	AspectRatioValidator func(string) error
	// DefaultAudio holds the default value on creation for the "audio" field.
	DefaultAudio bool
	// DefaultImageSource holds the default value on creation for the "image_source" field.
	DefaultImageSource string
	// ImageSourceValidator is a validator for the "image_source" field. It is called by the builders before save.
	ImageSourceValidator func(string) error
	// LocalInputNameValidator is a validator for the "local_input_name" field. It is called by the builders before save.
	LocalInputNameValidator func(string) error
	// RequestHashValidator is a validator for the "request_hash" field. It is called by the builders before save.
	RequestHashValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the VideoJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByUpstreamJobID orders the results by the upstream_job_id field.
func ByUpstreamJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamJobID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRequestedModel orders the results by the requested_model field.
func ByRequestedModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByPrompt orders the results by the prompt field.
func ByPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrompt, opts...).ToFunc()
}

// ByResolution orders the results by the resolution field.
func ByResolution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolution, opts...).ToFunc()
}

// ByDurationSeconds orders the results by the duration_seconds field.
func ByDurationSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDurationSeconds, opts...).ToFunc()
}

// ByAspectRatio orders the results by the aspect_ratio field.
func ByAspectRatio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAspectRatio, opts...).ToFunc()
}

// ByAudio orders the results by the audio field.
func ByAudio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAudio, opts...).ToFunc()
}

// ByImageSource orders the results by the image_source field.
func ByImageSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageSource, opts...).ToFunc()
}

// ByImageURL orders the results by the image_url field.
func ByImageURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImageURL, opts...).ToFunc()
}

// ByLocalInputName orders the results by the local_input_name field.
func ByLocalInputName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocalInputName, opts...).ToFunc()
}

// ByErrorMessage orders the results by the error_message field.
func ByErrorMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldErrorMessage, opts...).ToFunc()
}

// ByHoldAmount orders the results by the hold_amount field.
func ByHoldAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHoldAmount, opts...).ToFunc()
}

// ByActualCost orders the results by the actual_cost field.
func ByActualCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActualCost, opts...).ToFunc()
}

// ByRequestHash orders the results by the request_hash field.
func ByRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestHash, opts...).ToFunc()
}

// BySettledAt orders the results by the settled_at field.
func BySettledAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettledAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}
