// Code generated by ent, DO NOT EDIT.

package videojob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldID, id))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldJobID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldAPIKeyID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldAccountID, v))
}

// UpstreamJobID applies equality check predicate on the "upstream_job_id" field. It's identical to UpstreamJobIDEQ.
func UpstreamJobID(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldUpstreamJobID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldStatus, v))
}

// RequestedModel applies equality check predicate on the "requested_model" field. It's identical to RequestedModelEQ.
func RequestedModel(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldRequestedModel, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldUpstreamModel, v))
}

// Prompt applies equality check predicate on the "prompt" field. It's identical to PromptEQ.
func Prompt(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldPrompt, v))
}

// Resolution applies equality check predicate on the "resolution" field. It's identical to ResolutionEQ.
func Resolution(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldResolution, v))
}

// DurationSeconds applies equality check predicate on the "duration_seconds" field. It's identical to DurationSecondsEQ.
func DurationSeconds(v int) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldDurationSeconds, v))
}

// AspectRatio applies equality check predicate on the "aspect_ratio" field. It's identical to AspectRatioEQ.
func AspectRatio(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldAspectRatio, v))
}

// Audio applies equality check predicate on the "audio" field. It's identical to AudioEQ.
func Audio(v bool) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldAudio, v))
}

// ImageSource applies equality check predicate on the "image_source" field. It's identical to ImageSourceEQ.
func ImageSource(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldImageSource, v))
}

// ImageURL applies equality check predicate on the "image_url" field. It's identical to ImageURLEQ.
func ImageURL(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldImageURL, v))
}

// LocalInputName applies equality check predicate on the "local_input_name" field. It's identical to LocalInputNameEQ.
func LocalInputName(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldLocalInputName, v))
}

// ErrorMessage applies equality check predicate on the "error_message" field. It's identical to ErrorMessageEQ.
func ErrorMessage(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldErrorMessage, v))
}

// HoldAmount applies equality check predicate on the "hold_amount" field. It's identical to HoldAmountEQ.
func HoldAmount(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldHoldAmount, v))
}

// ActualCost applies equality check predicate on the "actual_cost" field. It's identical to ActualCostEQ.
func ActualCost(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldActualCost, v))
}

// RequestHash applies equality check predicate on the "request_hash" field. It's identical to RequestHashEQ.
func RequestHash(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldRequestHash, v))
}

// SettledAt applies equality check predicate on the "settled_at" field. It's identical to SettledAtEQ.
func SettledAt(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldSettledAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldFinishedAt, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldJobID, v))
}

// JobIDContains applies the Contains predicate on the "job_id" field.
func JobIDContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldJobID, v))
}

// JobIDHasPrefix applies the HasPrefix predicate on the "job_id" field.
func JobIDHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldJobID, v))
}

// JobIDHasSuffix applies the HasSuffix predicate on the "job_id" field.
func JobIDHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldJobID, v))
}

// JobIDEqualFold applies the EqualFold predicate on the "job_id" field.
func JobIDEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldJobID, v))
}

// JobIDContainsFold applies the ContainsFold predicate on the "job_id" field.
func JobIDContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldJobID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldAPIKeyID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldGroupID, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldAccountID, v))
}

// UpstreamJobIDEQ applies the EQ predicate on the "upstream_job_id" field.
func UpstreamJobIDEQ(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldUpstreamJobID, v))
}

// UpstreamJobIDNEQ applies the NEQ predicate on the "upstream_job_id" field.
func UpstreamJobIDNEQ(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldUpstreamJobID, v))
}

// UpstreamJobIDIn applies the In predicate on the "upstream_job_id" field.
func UpstreamJobIDIn(vs ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldUpstreamJobID, vs...))
}

// UpstreamJobIDNotIn applies the NotIn predicate on the "upstream_job_id" field.
func UpstreamJobIDNotIn(vs ...int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldUpstreamJobID, vs...))
}

// UpstreamJobIDGT applies the GT predicate on the "upstream_job_id" field.
func UpstreamJobIDGT(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldUpstreamJobID, v))
}

// UpstreamJobIDGTE applies the GTE predicate on the "upstream_job_id" field.
func UpstreamJobIDGTE(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldUpstreamJobID, v))
}

// UpstreamJobIDLT applies the LT predicate on the "upstream_job_id" field.
func UpstreamJobIDLT(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldUpstreamJobID, v))
}

// UpstreamJobIDLTE applies the LTE predicate on the "upstream_job_id" field.
func UpstreamJobIDLTE(v int64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldUpstreamJobID, v))
}

// UpstreamJobIDIsNil applies the IsNil predicate on the "upstream_job_id" field.
func UpstreamJobIDIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldUpstreamJobID))
}

// UpstreamJobIDNotNil applies the NotNil predicate on the "upstream_job_id" field.
func UpstreamJobIDNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldUpstreamJobID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldStatus, v))
}

// RequestedModelEQ applies the EQ predicate on the "requested_model" field.
func RequestedModelEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldRequestedModel, v))
}

// RequestedModelNEQ applies the NEQ predicate on the "requested_model" field.
func RequestedModelNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldRequestedModel, v))
}

// RequestedModelIn applies the In predicate on the "requested_model" field.
func RequestedModelIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldRequestedModel, vs...))
}

// RequestedModelNotIn applies the NotIn predicate on the "requested_model" field.
func RequestedModelNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldRequestedModel, vs...))
}

// RequestedModelGT applies the GT predicate on the "requested_model" field.
func RequestedModelGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldRequestedModel, v))
}

// RequestedModelGTE applies the GTE predicate on the "requested_model" field.
func RequestedModelGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldRequestedModel, v))
}

// RequestedModelLT applies the LT predicate on the "requested_model" field.
func RequestedModelLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldRequestedModel, v))
}

// RequestedModelLTE applies the LTE predicate on the "requested_model" field.
func RequestedModelLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldRequestedModel, v))
}

// RequestedModelContains applies the Contains predicate on the "requested_model" field.
func RequestedModelContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldRequestedModel, v))
}

// RequestedModelHasPrefix applies the HasPrefix predicate on the "requested_model" field.
func RequestedModelHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldRequestedModel, v))
}

// RequestedModelHasSuffix applies the HasSuffix predicate on the "requested_model" field.
func RequestedModelHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldRequestedModel, v))
}

// RequestedModelEqualFold applies the EqualFold predicate on the "requested_model" field.
func RequestedModelEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldRequestedModel, v))
}

// RequestedModelContainsFold applies the ContainsFold predicate on the "requested_model" field.
func RequestedModelContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldRequestedModel, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// PromptEQ applies the EQ predicate on the "prompt" field.
func PromptEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldPrompt, v))
}

// PromptNEQ applies the NEQ predicate on the "prompt" field.
func PromptNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldPrompt, v))
}

// PromptIn applies the In predicate on the "prompt" field.
func PromptIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldPrompt, vs...))
}

// PromptNotIn applies the NotIn predicate on the "prompt" field.
func PromptNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldPrompt, vs...))
}

// PromptGT applies the GT predicate on the "prompt" field.
func PromptGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldPrompt, v))
}

// PromptGTE applies the GTE predicate on the "prompt" field.
func PromptGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldPrompt, v))
}

// PromptLT applies the LT predicate on the "prompt" field.
func PromptLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldPrompt, v))
}

// PromptLTE applies the LTE predicate on the "prompt" field.
func PromptLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldPrompt, v))
}

// PromptContains applies the Contains predicate on the "prompt" field.
func PromptContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldPrompt, v))
}

// PromptHasPrefix applies the HasPrefix predicate on the "prompt" field.
func PromptHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldPrompt, v))
}

// PromptHasSuffix applies the HasSuffix predicate on the "prompt" field.
func PromptHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldPrompt, v))
}

// PromptEqualFold applies the EqualFold predicate on the "prompt" field.
func PromptEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldPrompt, v))
}

// PromptContainsFold applies the ContainsFold predicate on the "prompt" field.
func PromptContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldPrompt, v))
}

// ResolutionEQ applies the EQ predicate on the "resolution" field.
func ResolutionEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldResolution, v))
}

// ResolutionNEQ applies the NEQ predicate on the "resolution" field.
func ResolutionNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldResolution, v))
}

// ResolutionIn applies the In predicate on the "resolution" field.
func ResolutionIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldResolution, vs...))
}

// ResolutionNotIn applies the NotIn predicate on the "resolution" field.
func ResolutionNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldResolution, vs...))
}

// ResolutionGT applies the GT predicate on the "resolution" field.
func ResolutionGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldResolution, v))
}

// ResolutionGTE applies the GTE predicate on the "resolution" field.
func ResolutionGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldResolution, v))
}

// ResolutionLT applies the LT predicate on the "resolution" field.
func ResolutionLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldResolution, v))
}

// ResolutionLTE applies the LTE predicate on the "resolution" field.
func ResolutionLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldResolution, v))
}

// ResolutionContains applies the Contains predicate on the "resolution" field.
func ResolutionContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldResolution, v))
}

// ResolutionHasPrefix applies the HasPrefix predicate on the "resolution" field.
func ResolutionHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldResolution, v))
}

// ResolutionHasSuffix applies the HasSuffix predicate on the "resolution" field.
func ResolutionHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldResolution, v))
}

// ResolutionEqualFold applies the EqualFold predicate on the "resolution" field.
func ResolutionEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldResolution, v))
}

// ResolutionContainsFold applies the ContainsFold predicate on the "resolution" field.
func ResolutionContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldResolution, v))
}

// DurationSecondsEQ applies the EQ predicate on the "duration_seconds" field.
func DurationSecondsEQ(v int) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldDurationSeconds, v))
}

// DurationSecondsNEQ applies the NEQ predicate on the "duration_seconds" field.
func DurationSecondsNEQ(v int) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldDurationSeconds, v))
}

// DurationSecondsIn applies the In predicate on the "duration_seconds" field.
func DurationSecondsIn(vs ...int) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldDurationSeconds, vs...))
}

// DurationSecondsNotIn applies the NotIn predicate on the "duration_seconds" field.
func DurationSecondsNotIn(vs ...int) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldDurationSeconds, vs...))
}

// DurationSecondsGT applies the GT predicate on the "duration_seconds" field.
func DurationSecondsGT(v int) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldDurationSeconds, v))
}

// DurationSecondsGTE applies the GTE predicate on the "duration_seconds" field.
func DurationSecondsGTE(v int) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldDurationSeconds, v))
}

// DurationSecondsLT applies the LT predicate on the "duration_seconds" field.
func DurationSecondsLT(v int) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldDurationSeconds, v))
}

// DurationSecondsLTE applies the LTE predicate on the "duration_seconds" field.
func DurationSecondsLTE(v int) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldDurationSeconds, v))
}

// AspectRatioEQ applies the EQ predicate on the "aspect_ratio" field.
func AspectRatioEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldAspectRatio, v))
}

// AspectRatioNEQ applies the NEQ predicate on the "aspect_ratio" field.
func AspectRatioNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldAspectRatio, v))
}

// AspectRatioIn applies the In predicate on the "aspect_ratio" field.
func AspectRatioIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldAspectRatio, vs...))
}

// AspectRatioNotIn applies the NotIn predicate on the "aspect_ratio" field.
func AspectRatioNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldAspectRatio, vs...))
}

// AspectRatioGT applies the GT predicate on the "aspect_ratio" field.
func AspectRatioGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldAspectRatio, v))
}

// AspectRatioGTE applies the GTE predicate on the "aspect_ratio" field.
func AspectRatioGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldAspectRatio, v))
}

// AspectRatioLT applies the LT predicate on the "aspect_ratio" field.
func AspectRatioLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldAspectRatio, v))
}

// AspectRatioLTE applies the LTE predicate on the "aspect_ratio" field.
func AspectRatioLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldAspectRatio, v))
}

// AspectRatioContains applies the Contains predicate on the "aspect_ratio" field.
func AspectRatioContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldAspectRatio, v))
}

// AspectRatioHasPrefix applies the HasPrefix predicate on the "aspect_ratio" field.
func AspectRatioHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldAspectRatio, v))
}

// AspectRatioHasSuffix applies the HasSuffix predicate on the "aspect_ratio" field.
func AspectRatioHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldAspectRatio, v))
}

// AspectRatioEqualFold applies the EqualFold predicate on the "aspect_ratio" field.
func AspectRatioEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldAspectRatio, v))
}

// AspectRatioContainsFold applies the ContainsFold predicate on the "aspect_ratio" field.
func AspectRatioContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldAspectRatio, v))
}

// AudioEQ applies the EQ predicate on the "audio" field.
func AudioEQ(v bool) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldAudio, v))
}

// AudioNEQ applies the NEQ predicate on the "audio" field.
func AudioNEQ(v bool) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldAudio, v))
}

// ImageSourceEQ applies the EQ predicate on the "image_source" field.
func ImageSourceEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldImageSource, v))
}

// ImageSourceNEQ applies the NEQ predicate on the "image_source" field.
func ImageSourceNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldImageSource, v))
}

// ImageSourceIn applies the In predicate on the "image_source" field.
func ImageSourceIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldImageSource, vs...))
}

// ImageSourceNotIn applies the NotIn predicate on the "image_source" field.
func ImageSourceNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldImageSource, vs...))
}

// ImageSourceGT applies the GT predicate on the "image_source" field.
func ImageSourceGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldImageSource, v))
}

// ImageSourceGTE applies the GTE predicate on the "image_source" field.
func ImageSourceGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldImageSource, v))
}

// ImageSourceLT applies the LT predicate on the "image_source" field.
func ImageSourceLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldImageSource, v))
}

// ImageSourceLTE applies the LTE predicate on the "image_source" field.
func ImageSourceLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldImageSource, v))
}

// ImageSourceContains applies the Contains predicate on the "image_source" field.
func ImageSourceContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldImageSource, v))
}

// ImageSourceHasPrefix applies the HasPrefix predicate on the "image_source" field.
func ImageSourceHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldImageSource, v))
}

// ImageSourceHasSuffix applies the HasSuffix predicate on the "image_source" field.
func ImageSourceHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldImageSource, v))
}

// ImageSourceEqualFold applies the EqualFold predicate on the "image_source" field.
func ImageSourceEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldImageSource, v))
}

// ImageSourceContainsFold applies the ContainsFold predicate on the "image_source" field.
func ImageSourceContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldImageSource, v))
}

// ImageURLEQ applies the EQ predicate on the "image_url" field.
func ImageURLEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldImageURL, v))
}

// ImageURLNEQ applies the NEQ predicate on the "image_url" field.
func ImageURLNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldImageURL, v))
}

// ImageURLIn applies the In predicate on the "image_url" field.
func ImageURLIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldImageURL, vs...))
}

// ImageURLNotIn applies the NotIn predicate on the "image_url" field.
func ImageURLNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldImageURL, vs...))
}

// ImageURLGT applies the GT predicate on the "image_url" field.
func ImageURLGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldImageURL, v))
}

// ImageURLGTE applies the GTE predicate on the "image_url" field.
func ImageURLGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldImageURL, v))
}

// ImageURLLT applies the LT predicate on the "image_url" field.
func ImageURLLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldImageURL, v))
}

// ImageURLLTE applies the LTE predicate on the "image_url" field.
func ImageURLLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldImageURL, v))
}

// ImageURLContains applies the Contains predicate on the "image_url" field.
func ImageURLContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldImageURL, v))
}

// ImageURLHasPrefix applies the HasPrefix predicate on the "image_url" field.
func ImageURLHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldImageURL, v))
}

// ImageURLHasSuffix applies the HasSuffix predicate on the "image_url" field.
func ImageURLHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldImageURL, v))
}

// ImageURLIsNil applies the IsNil predicate on the "image_url" field.
func ImageURLIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldImageURL))
}

// ImageURLNotNil applies the NotNil predicate on the "image_url" field.
func ImageURLNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldImageURL))
}

// ImageURLEqualFold applies the EqualFold predicate on the "image_url" field.
func ImageURLEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldImageURL, v))
}

// ImageURLContainsFold applies the ContainsFold predicate on the "image_url" field.
func ImageURLContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldImageURL, v))
}

// LocalInputNameEQ applies the EQ predicate on the "local_input_name" field.
func LocalInputNameEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldLocalInputName, v))
}

// LocalInputNameNEQ applies the NEQ predicate on the "local_input_name" field.
func LocalInputNameNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldLocalInputName, v))
}

// LocalInputNameIn applies the In predicate on the "local_input_name" field.
func LocalInputNameIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldLocalInputName, vs...))
}

// LocalInputNameNotIn applies the NotIn predicate on the "local_input_name" field.
func LocalInputNameNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldLocalInputName, vs...))
}

// LocalInputNameGT applies the GT predicate on the "local_input_name" field.
func LocalInputNameGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldLocalInputName, v))
}

// LocalInputNameGTE applies the GTE predicate on the "local_input_name" field.
func LocalInputNameGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldLocalInputName, v))
}

// LocalInputNameLT applies the LT predicate on the "local_input_name" field.
func LocalInputNameLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldLocalInputName, v))
}

// LocalInputNameLTE applies the LTE predicate on the "local_input_name" field.
func LocalInputNameLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldLocalInputName, v))
}

// LocalInputNameContains applies the Contains predicate on the "local_input_name" field.
func LocalInputNameContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldLocalInputName, v))
}

// LocalInputNameHasPrefix applies the HasPrefix predicate on the "local_input_name" field.
func LocalInputNameHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldLocalInputName, v))
}

// LocalInputNameHasSuffix applies the HasSuffix predicate on the "local_input_name" field.
func LocalInputNameHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldLocalInputName, v))
}

// LocalInputNameIsNil applies the IsNil predicate on the "local_input_name" field.
func LocalInputNameIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldLocalInputName))
}

// LocalInputNameNotNil applies the NotNil predicate on the "local_input_name" field.
func LocalInputNameNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldLocalInputName))
}

// LocalInputNameEqualFold applies the EqualFold predicate on the "local_input_name" field.
func LocalInputNameEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldLocalInputName, v))
}

// LocalInputNameContainsFold applies the ContainsFold predicate on the "local_input_name" field.
func LocalInputNameContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldLocalInputName, v))
}

// ResultIsNil applies the IsNil predicate on the "result" field.
func ResultIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldResult))
}

// ResultNotNil applies the NotNil predicate on the "result" field.
func ResultNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldResult))
}

// ErrorMessageEQ applies the EQ predicate on the "error_message" field.
func ErrorMessageEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldErrorMessage, v))
}

// ErrorMessageNEQ applies the NEQ predicate on the "error_message" field.
func ErrorMessageNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldErrorMessage, v))
}

// ErrorMessageIn applies the In predicate on the "error_message" field.
func ErrorMessageIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldErrorMessage, vs...))
}

// ErrorMessageNotIn applies the NotIn predicate on the "error_message" field.
func ErrorMessageNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldErrorMessage, vs...))
}

// ErrorMessageGT applies the GT predicate on the "error_message" field.
func ErrorMessageGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldErrorMessage, v))
}

// ErrorMessageGTE applies the GTE predicate on the "error_message" field.
func ErrorMessageGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldErrorMessage, v))
}

// ErrorMessageLT applies the LT predicate on the "error_message" field.
func ErrorMessageLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldErrorMessage, v))
}

// ErrorMessageLTE applies the LTE predicate on the "error_message" field.
func ErrorMessageLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldErrorMessage, v))
}

// ErrorMessageContains applies the Contains predicate on the "error_message" field.
func ErrorMessageContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldErrorMessage, v))
}

// ErrorMessageHasPrefix applies the HasPrefix predicate on the "error_message" field.
func ErrorMessageHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldErrorMessage, v))
}

// ErrorMessageHasSuffix applies the HasSuffix predicate on the "error_message" field.
func ErrorMessageHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldErrorMessage, v))
}

// ErrorMessageIsNil applies the IsNil predicate on the "error_message" field.
func ErrorMessageIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldErrorMessage))
}

// ErrorMessageNotNil applies the NotNil predicate on the "error_message" field.
func ErrorMessageNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldErrorMessage))
}

// ErrorMessageEqualFold applies the EqualFold predicate on the "error_message" field.
func ErrorMessageEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldErrorMessage, v))
}

// ErrorMessageContainsFold applies the ContainsFold predicate on the "error_message" field.
func ErrorMessageContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldErrorMessage, v))
}

// HoldAmountEQ applies the EQ predicate on the "hold_amount" field.
func HoldAmountEQ(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldHoldAmount, v))
}

// HoldAmountNEQ applies the NEQ predicate on the "hold_amount" field.
func HoldAmountNEQ(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldHoldAmount, v))
}

// HoldAmountIn applies the In predicate on the "hold_amount" field.
func HoldAmountIn(vs ...float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldHoldAmount, vs...))
}

// HoldAmountNotIn applies the NotIn predicate on the "hold_amount" field.
func HoldAmountNotIn(vs ...float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldHoldAmount, vs...))
}

// HoldAmountGT applies the GT predicate on the "hold_amount" field.
func HoldAmountGT(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldHoldAmount, v))
}

// HoldAmountGTE applies the GTE predicate on the "hold_amount" field.
func HoldAmountGTE(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldHoldAmount, v))
}

// HoldAmountLT applies the LT predicate on the "hold_amount" field.
func HoldAmountLT(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldHoldAmount, v))
}

// HoldAmountLTE applies the LTE predicate on the "hold_amount" field.
func HoldAmountLTE(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldHoldAmount, v))
}

// HoldAmountIsNil applies the IsNil predicate on the "hold_amount" field.
func HoldAmountIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldHoldAmount))
}

// HoldAmountNotNil applies the NotNil predicate on the "hold_amount" field.
func HoldAmountNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldHoldAmount))
}

// ActualCostEQ applies the EQ predicate on the "actual_cost" field.
func ActualCostEQ(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldActualCost, v))
}

// ActualCostNEQ applies the NEQ predicate on the "actual_cost" field.
func ActualCostNEQ(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldActualCost, v))
}

// ActualCostIn applies the In predicate on the "actual_cost" field.
func ActualCostIn(vs ...float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldActualCost, vs...))
}

// ActualCostNotIn applies the NotIn predicate on the "actual_cost" field.
func ActualCostNotIn(vs ...float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldActualCost, vs...))
}

// ActualCostGT applies the GT predicate on the "actual_cost" field.
func ActualCostGT(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldActualCost, v))
}

// ActualCostGTE applies the GTE predicate on the "actual_cost" field.
func ActualCostGTE(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldActualCost, v))
}

// ActualCostLT applies the LT predicate on the "actual_cost" field.
func ActualCostLT(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldActualCost, v))
}

// ActualCostLTE applies the LTE predicate on the "actual_cost" field.
func ActualCostLTE(v float64) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldActualCost, v))
}

// ActualCostIsNil applies the IsNil predicate on the "actual_cost" field.
func ActualCostIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldActualCost))
}

// ActualCostNotNil applies the NotNil predicate on the "actual_cost" field.
func ActualCostNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldActualCost))
}

// BillingSnapshotIsNil applies the IsNil predicate on the "billing_snapshot" field.
func BillingSnapshotIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldBillingSnapshot))
}

// BillingSnapshotNotNil applies the NotNil predicate on the "billing_snapshot" field.
func BillingSnapshotNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldBillingSnapshot))
}

// RequestHashEQ applies the EQ predicate on the "request_hash" field.
func RequestHashEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldRequestHash, v))
}

// RequestHashNEQ applies the NEQ predicate on the "request_hash" field.
func RequestHashNEQ(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldRequestHash, v))
}

// RequestHashIn applies the In predicate on the "request_hash" field.
func RequestHashIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldRequestHash, vs...))
}

// RequestHashNotIn applies the NotIn predicate on the "request_hash" field.
func RequestHashNotIn(vs ...string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldRequestHash, vs...))
}

// RequestHashGT applies the GT predicate on the "request_hash" field.
func RequestHashGT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldRequestHash, v))
}

// RequestHashGTE applies the GTE predicate on the "request_hash" field.
func RequestHashGTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldRequestHash, v))
}

// RequestHashLT applies the LT predicate on the "request_hash" field.
func RequestHashLT(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldRequestHash, v))
}

// RequestHashLTE applies the LTE predicate on the "request_hash" field.
func RequestHashLTE(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldRequestHash, v))
}

// RequestHashContains applies the Contains predicate on the "request_hash" field.
func RequestHashContains(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContains(FieldRequestHash, v))
}

// RequestHashHasPrefix applies the HasPrefix predicate on the "request_hash" field.
func RequestHashHasPrefix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasPrefix(FieldRequestHash, v))
}

// RequestHashHasSuffix applies the HasSuffix predicate on the "request_hash" field.
func RequestHashHasSuffix(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldHasSuffix(FieldRequestHash, v))
}

// RequestHashEqualFold applies the EqualFold predicate on the "request_hash" field.
func RequestHashEqualFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEqualFold(FieldRequestHash, v))
}

// RequestHashContainsFold applies the ContainsFold predicate on the "request_hash" field.
func RequestHashContainsFold(v string) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldContainsFold(FieldRequestHash, v))
}

// SettledAtEQ applies the EQ predicate on the "settled_at" field.
func SettledAtEQ(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldSettledAt, v))
}

// SettledAtNEQ applies the NEQ predicate on the "settled_at" field.
func SettledAtNEQ(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldSettledAt, v))
}

// SettledAtIn applies the In predicate on the "settled_at" field.
func SettledAtIn(vs ...time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldSettledAt, vs...))
}

// SettledAtNotIn applies the NotIn predicate on the "settled_at" field.
func SettledAtNotIn(vs ...time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldSettledAt, vs...))
}

// SettledAtGT applies the GT predicate on the "settled_at" field.
func SettledAtGT(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldSettledAt, v))
}

// SettledAtGTE applies the GTE predicate on the "settled_at" field.
func SettledAtGTE(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldSettledAt, v))
}

// SettledAtLT applies the LT predicate on the "settled_at" field.
func SettledAtLT(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldSettledAt, v))
}

// SettledAtLTE applies the LTE predicate on the "settled_at" field.
func SettledAtLTE(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldSettledAt, v))
}

// SettledAtIsNil applies the IsNil predicate on the "settled_at" field.
func SettledAtIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldSettledAt))
}

// SettledAtNotNil applies the NotNil predicate on the "settled_at" field.
func SettledAtNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldSettledAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.VideoJob {
	return predicate.VideoJob(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.VideoJob {
	return predicate.VideoJob(sql.FieldNotNull(FieldFinishedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VideoJob) predicate.VideoJob {
	return predicate.VideoJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VideoJob) predicate.VideoJob {
	return predicate.VideoJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VideoJob) predicate.VideoJob {
	return predicate.VideoJob(sql.NotPredicates(p))
}
