// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/videojob"
)

// VideoJobUpdate is the builder for updating VideoJob entities.
type VideoJobUpdate struct {
	config
	hooks    []Hook
	mutation *VideoJobMutation
}

// Where appends a list predicates to the VideoJobUpdate builder.
func (_u *VideoJobUpdate) Where(ps ...predicate.VideoJob) *VideoJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpstreamJobID sets the "upstream_job_id" field.
func (_u *VideoJobUpdate) SetUpstreamJobID(v int64) *VideoJobUpdate {
	_u.mutation.ResetUpstreamJobID()
	_u.mutation.SetUpstreamJobID(v)
	return _u
}

// SetNillableUpstreamJobID sets the "upstream_job_id" field if the given value is not nil.
func (_u *VideoJobUpdate) SetNillableUpstreamJobID(v *int64) *VideoJobUpdate {
	if v != nil {
		_u.SetUpstreamJobID(*v)
	}
	return _u
}

// AddUpstreamJobID adds value to the "upstream_job_id" field.
func (_u *VideoJobUpdate) AddUpstreamJobID(v int64) *VideoJobUpdate {
	_u.mutation.AddUpstreamJobID(v)
	return _u
}

// ClearUpstreamJobID clears the value of the "upstream_job_id" field.
func (_u *VideoJobUpdate) ClearUpstreamJobID() *VideoJobUpdate {
	_u.mutation.ClearUpstreamJobID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoJobUpdate) SetStatus(v string) *VideoJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoJobUpdate) SetNillableStatus(v *string) *VideoJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *VideoJobUpdate) SetResult(v json.RawMessage) *VideoJobUpdate {
	_u.mutation.SetResult(v)
	return _u
}

// AppendResult appends value to the "result" field.
func (_u *VideoJobUpdate) AppendResult(v json.RawMessage) *VideoJobUpdate {
	_u.mutation.AppendResult(v)
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *VideoJobUpdate) ClearResult() *VideoJobUpdate {
	_u.mutation.ClearResult()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *VideoJobUpdate) SetErrorMessage(v string) *VideoJobUpdate {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *VideoJobUpdate) SetNillableErrorMessage(v *string) *VideoJobUpdate {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *VideoJobUpdate) ClearErrorMessage() *VideoJobUpdate {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetHoldAmount sets the "hold_amount" field.
func (_u *VideoJobUpdate) SetHoldAmount(v float64) *VideoJobUpdate {
	_u.mutation.ResetHoldAmount()
	_u.mutation.SetHoldAmount(v)
	return _u
}

// SetNillableHoldAmount sets the "hold_amount" field if the given value is not nil.
func (_u *VideoJobUpdate) SetNillableHoldAmount(v *float64) *VideoJobUpdate {
	if v != nil {
		_u.SetHoldAmount(*v)
	}
	return _u
}

// AddHoldAmount adds value to the "hold_amount" field.
func (_u *VideoJobUpdate) AddHoldAmount(v float64) *VideoJobUpdate {
	_u.mutation.AddHoldAmount(v)
	return _u
}

// ClearHoldAmount clears the value of the "hold_amount" field.
func (_u *VideoJobUpdate) ClearHoldAmount() *VideoJobUpdate {
	_u.mutation.ClearHoldAmount()
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *VideoJobUpdate) SetActualCost(v float64) *VideoJobUpdate {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *VideoJobUpdate) SetNillableActualCost(v *float64) *VideoJobUpdate {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *VideoJobUpdate) AddActualCost(v float64) *VideoJobUpdate {
	_u.mutation.AddActualCost(v)
	return _u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (_u *VideoJobUpdate) ClearActualCost() *VideoJobUpdate {
	_u.mutation.ClearActualCost()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *VideoJobUpdate) SetSettledAt(v time.Time) *VideoJobUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *VideoJobUpdate) SetNillableSettledAt(v *time.Time) *VideoJobUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *VideoJobUpdate) ClearSettledAt() *VideoJobUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoJobUpdate) SetUpdatedAt(v time.Time) *VideoJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *VideoJobUpdate) SetStartedAt(v time.Time) *VideoJobUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *VideoJobUpdate) SetNillableStartedAt(v *time.Time) *VideoJobUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *VideoJobUpdate) ClearStartedAt() *VideoJobUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *VideoJobUpdate) SetFinishedAt(v time.Time) *VideoJobUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *VideoJobUpdate) SetNillableFinishedAt(v *time.Time) *VideoJobUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *VideoJobUpdate) ClearFinishedAt() *VideoJobUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the VideoJobMutation object of the builder.
func (_u *VideoJobUpdate) Mutation() *VideoJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *VideoJobUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *VideoJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoJobUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videojob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoJobUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := videojob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoJob.status": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videojob.Table, videojob.Columns, sqlgraph.NewFieldSpec(videojob.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpstreamJobID(); ok {
		_spec.SetField(videojob.FieldUpstreamJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamJobID(); ok {
		_spec.AddField(videojob.FieldUpstreamJobID, field.TypeInt64, value)
	}
	if _u.mutation.UpstreamJobIDCleared() {
		_spec.ClearField(videojob.FieldUpstreamJobID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videojob.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(videojob.FieldImageURL, field.TypeString)
	}
	if _u.mutation.LocalInputNameCleared() {
		_spec.ClearField(videojob.FieldLocalInputName, field.TypeString)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(videojob.FieldResult, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResult(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, videojob.FieldResult, value)
		})
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(videojob.FieldResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(videojob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(videojob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.HoldAmount(); ok {
		_spec.SetField(videojob.FieldHoldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHoldAmount(); ok {
		_spec.AddField(videojob.FieldHoldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.HoldAmountCleared() {
		_spec.ClearField(videojob.FieldHoldAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(videojob.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(videojob.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.ActualCostCleared() {
		_spec.ClearField(videojob.FieldActualCost, field.TypeFloat64)
	}
	if _u.mutation.BillingSnapshotCleared() {
		_spec.ClearField(videojob.FieldBillingSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(videojob.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(videojob.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videojob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(videojob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(videojob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(videojob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(videojob.FieldFinishedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videojob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// VideoJobUpdateOne is the builder for updating a single VideoJob entity.
type VideoJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *VideoJobMutation
}

// SetUpstreamJobID sets the "upstream_job_id" field.
func (_u *VideoJobUpdateOne) SetUpstreamJobID(v int64) *VideoJobUpdateOne {
	_u.mutation.ResetUpstreamJobID()
	_u.mutation.SetUpstreamJobID(v)
	return _u
}

// SetNillableUpstreamJobID sets the "upstream_job_id" field if the given value is not nil.
func (_u *VideoJobUpdateOne) SetNillableUpstreamJobID(v *int64) *VideoJobUpdateOne {
	if v != nil {
		_u.SetUpstreamJobID(*v)
	}
	return _u
}

// AddUpstreamJobID adds value to the "upstream_job_id" field.
func (_u *VideoJobUpdateOne) AddUpstreamJobID(v int64) *VideoJobUpdateOne {
	_u.mutation.AddUpstreamJobID(v)
	return _u
}

// ClearUpstreamJobID clears the value of the "upstream_job_id" field.
func (_u *VideoJobUpdateOne) ClearUpstreamJobID() *VideoJobUpdateOne {
	_u.mutation.ClearUpstreamJobID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *VideoJobUpdateOne) SetStatus(v string) *VideoJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *VideoJobUpdateOne) SetNillableStatus(v *string) *VideoJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetResult sets the "result" field.
func (_u *VideoJobUpdateOne) SetResult(v json.RawMessage) *VideoJobUpdateOne {
	_u.mutation.SetResult(v)
	return _u
}

// AppendResult appends value to the "result" field.
func (_u *VideoJobUpdateOne) AppendResult(v json.RawMessage) *VideoJobUpdateOne {
	_u.mutation.AppendResult(v)
	return _u
}

// ClearResult clears the value of the "result" field.
func (_u *VideoJobUpdateOne) ClearResult() *VideoJobUpdateOne {
	_u.mutation.ClearResult()
	return _u
}

// SetErrorMessage sets the "error_message" field.
func (_u *VideoJobUpdateOne) SetErrorMessage(v string) *VideoJobUpdateOne {
	_u.mutation.SetErrorMessage(v)
	return _u
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_u *VideoJobUpdateOne) SetNillableErrorMessage(v *string) *VideoJobUpdateOne {
	if v != nil {
		_u.SetErrorMessage(*v)
	}
	return _u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (_u *VideoJobUpdateOne) ClearErrorMessage() *VideoJobUpdateOne {
	_u.mutation.ClearErrorMessage()
	return _u
}

// SetHoldAmount sets the "hold_amount" field.
func (_u *VideoJobUpdateOne) SetHoldAmount(v float64) *VideoJobUpdateOne {
	_u.mutation.ResetHoldAmount()
	_u.mutation.SetHoldAmount(v)
	return _u
}

// SetNillableHoldAmount sets the "hold_amount" field if the given value is not nil.
func (_u *VideoJobUpdateOne) SetNillableHoldAmount(v *float64) *VideoJobUpdateOne {
	if v != nil {
		_u.SetHoldAmount(*v)
	}
	return _u
}

// AddHoldAmount adds value to the "hold_amount" field.
func (_u *VideoJobUpdateOne) AddHoldAmount(v float64) *VideoJobUpdateOne {
	_u.mutation.AddHoldAmount(v)
	return _u
}

// ClearHoldAmount clears the value of the "hold_amount" field.
func (_u *VideoJobUpdateOne) ClearHoldAmount() *VideoJobUpdateOne {
	_u.mutation.ClearHoldAmount()
	return _u
}

// SetActualCost sets the "actual_cost" field.
func (_u *VideoJobUpdateOne) SetActualCost(v float64) *VideoJobUpdateOne {
	_u.mutation.ResetActualCost()
	_u.mutation.SetActualCost(v)
	return _u
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_u *VideoJobUpdateOne) SetNillableActualCost(v *float64) *VideoJobUpdateOne {
	if v != nil {
		_u.SetActualCost(*v)
	}
	return _u
}

// AddActualCost adds value to the "actual_cost" field.
func (_u *VideoJobUpdateOne) AddActualCost(v float64) *VideoJobUpdateOne {
	_u.mutation.AddActualCost(v)
	return _u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (_u *VideoJobUpdateOne) ClearActualCost() *VideoJobUpdateOne {
	_u.mutation.ClearActualCost()
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *VideoJobUpdateOne) SetSettledAt(v time.Time) *VideoJobUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *VideoJobUpdateOne) SetNillableSettledAt(v *time.Time) *VideoJobUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *VideoJobUpdateOne) ClearSettledAt() *VideoJobUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *VideoJobUpdateOne) SetUpdatedAt(v time.Time) *VideoJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *VideoJobUpdateOne) SetStartedAt(v time.Time) *VideoJobUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *VideoJobUpdateOne) SetNillableStartedAt(v *time.Time) *VideoJobUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *VideoJobUpdateOne) ClearStartedAt() *VideoJobUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *VideoJobUpdateOne) SetFinishedAt(v time.Time) *VideoJobUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *VideoJobUpdateOne) SetNillableFinishedAt(v *time.Time) *VideoJobUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *VideoJobUpdateOne) ClearFinishedAt() *VideoJobUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// Mutation returns the VideoJobMutation object of the builder.
func (_u *VideoJobUpdateOne) Mutation() *VideoJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the VideoJobUpdate builder.
func (_u *VideoJobUpdateOne) Where(ps ...predicate.VideoJob) *VideoJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *VideoJobUpdateOne) Select(field string, fields ...string) *VideoJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated VideoJob entity.
func (_u *VideoJobUpdateOne) Save(ctx context.Context) (*VideoJob, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *VideoJobUpdateOne) SaveX(ctx context.Context) *VideoJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *VideoJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *VideoJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *VideoJobUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := videojob.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *VideoJobUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := videojob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoJob.status": %w`, err)}
		}
	}
	return nil
}

func (_u *VideoJobUpdateOne) sqlSave(ctx context.Context) (_node *VideoJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(videojob.Table, videojob.Columns, sqlgraph.NewFieldSpec(videojob.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "VideoJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, videojob.FieldID)
		for _, f := range fields {
			if !videojob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != videojob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpstreamJobID(); ok {
		_spec.SetField(videojob.FieldUpstreamJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpstreamJobID(); ok {
		_spec.AddField(videojob.FieldUpstreamJobID, field.TypeInt64, value)
	}
	if _u.mutation.UpstreamJobIDCleared() {
		_spec.ClearField(videojob.FieldUpstreamJobID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(videojob.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(videojob.FieldImageURL, field.TypeString)
	}
	if _u.mutation.LocalInputNameCleared() {
		_spec.ClearField(videojob.FieldLocalInputName, field.TypeString)
	}
	if value, ok := _u.mutation.Result(); ok {
		_spec.SetField(videojob.FieldResult, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedResult(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, videojob.FieldResult, value)
		})
	}
	if _u.mutation.ResultCleared() {
		_spec.ClearField(videojob.FieldResult, field.TypeJSON)
	}
	if value, ok := _u.mutation.ErrorMessage(); ok {
		_spec.SetField(videojob.FieldErrorMessage, field.TypeString, value)
	}
	if _u.mutation.ErrorMessageCleared() {
		_spec.ClearField(videojob.FieldErrorMessage, field.TypeString)
	}
	if value, ok := _u.mutation.HoldAmount(); ok {
		_spec.SetField(videojob.FieldHoldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedHoldAmount(); ok {
		_spec.AddField(videojob.FieldHoldAmount, field.TypeFloat64, value)
	}
	if _u.mutation.HoldAmountCleared() {
		_spec.ClearField(videojob.FieldHoldAmount, field.TypeFloat64)
	}
	if value, ok := _u.mutation.ActualCost(); ok {
		_spec.SetField(videojob.FieldActualCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedActualCost(); ok {
		_spec.AddField(videojob.FieldActualCost, field.TypeFloat64, value)
	}
	if _u.mutation.ActualCostCleared() {
		_spec.ClearField(videojob.FieldActualCost, field.TypeFloat64)
	}
	if _u.mutation.BillingSnapshotCleared() {
		_spec.ClearField(videojob.FieldBillingSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(videojob.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(videojob.FieldSettledAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(videojob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(videojob.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(videojob.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(videojob.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(videojob.FieldFinishedAt, field.TypeTime)
	}
	_node = &VideoJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{videojob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
