// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/videojob"
)

// VideoJob is the model entity for the VideoJob schema.
type VideoJob struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID string `json:"job_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID int64 `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// UpstreamJobID holds the value of the "upstream_job_id" field.
	UpstreamJobID *int64 `json:"upstream_job_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// RequestedModel holds the value of the "requested_model" field.
	RequestedModel string `json:"requested_model,omitempty"`
	// UpstreamModel holds the value of the "upstream_model" field.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// Prompt holds the value of the "prompt" field.
	Prompt string `json:"prompt,omitempty"`
	// Resolution holds the value of the "resolution" field.
	Resolution string `json:"resolution,omitempty"`
	// DurationSeconds holds the value of the "duration_seconds" field.
	DurationSeconds int `json:"duration_seconds,omitempty"`
	// AspectRatio holds the value of the "aspect_ratio" field.
	AspectRatio string `json:"aspect_ratio,omitempty"`
	// Audio holds the value of the "audio" field.
	Audio bool `json:"audio,omitempty"`
	// ImageSource holds the value of the "image_source" field.
	ImageSource string `json:"image_source,omitempty"`
	// ImageURL holds the value of the "image_url" field.
	ImageURL *string `json:"image_url,omitempty"`
	// LocalInputName holds the value of the "local_input_name" field.
	LocalInputName *string `json:"local_input_name,omitempty"`
	// Result holds the value of the "result" field.
	Result json.RawMessage `json:"result,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// HoldAmount holds the value of the "hold_amount" field.
	HoldAmount *float64 `json:"hold_amount,omitempty"`
	// ActualCost holds the value of the "actual_cost" field.
	ActualCost *float64 `json:"actual_cost,omitempty"`
	// BillingSnapshot holds the value of the "billing_snapshot" field.
	BillingSnapshot json.RawMessage `json:"billing_snapshot,omitempty"`
	// RequestHash holds the value of the "request_hash" field.
	RequestHash string `json:"request_hash,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt *time.Time `json:"settled_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt   *time.Time `json:"finished_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VideoJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case videojob.FieldResult, videojob.FieldBillingSnapshot:
			values[i] = new([]byte)
		case videojob.FieldAudio:
			values[i] = new(sql.NullBool)
		case videojob.FieldHoldAmount, videojob.FieldActualCost:
			values[i] = new(sql.NullFloat64)
		case videojob.FieldID, videojob.FieldUserID, videojob.FieldAPIKeyID, videojob.FieldGroupID, videojob.FieldAccountID, videojob.FieldUpstreamJobID, videojob.FieldDurationSeconds:
			values[i] = new(sql.NullInt64)
		case videojob.FieldJobID, videojob.FieldStatus, videojob.FieldRequestedModel, videojob.FieldUpstreamModel, videojob.FieldPrompt, videojob.FieldResolution, videojob.FieldAspectRatio, videojob.FieldImageSource, videojob.FieldImageURL, videojob.FieldLocalInputName, videojob.FieldErrorMessage, videojob.FieldRequestHash:
			values[i] = new(sql.NullString)
		case videojob.FieldSettledAt, videojob.FieldCreatedAt, videojob.FieldUpdatedAt, videojob.FieldStartedAt, videojob.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VideoJob fields.
func (_m *VideoJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case videojob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case videojob.FieldJobID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.String
			}
		case videojob.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case videojob.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case videojob.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = value.Int64
			}
		case videojob.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case videojob.FieldUpstreamJobID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_job_id", values[i])
			} else if value.Valid {
				_m.UpstreamJobID = new(int64)
				*_m.UpstreamJobID = value.Int64
			}
		case videojob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case videojob.FieldRequestedModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field requested_model", values[i])
			} else if value.Valid {
				_m.RequestedModel = value.String
			}
		case videojob.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case videojob.FieldPrompt:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prompt", values[i])
			} else if value.Valid {
				_m.Prompt = value.String
			}
		case videojob.FieldResolution:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolution", values[i])
			} else if value.Valid {
				_m.Resolution = value.String
			}
		case videojob.FieldDurationSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_seconds", values[i])
			} else if value.Valid {
				_m.DurationSeconds = int(value.Int64)
			}
		case videojob.FieldAspectRatio:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field aspect_ratio", values[i])
			} else if value.Valid {
				_m.AspectRatio = value.String
			}
		case videojob.FieldAudio:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field audio", values[i])
			} else if value.Valid {
				_m.Audio = value.Bool
			}
		case videojob.FieldImageSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_source", values[i])
			} else if value.Valid {
				_m.ImageSource = value.String
			}
		case videojob.FieldImageURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_url", values[i])
			} else if value.Valid {
				_m.ImageURL = new(string)
				*_m.ImageURL = value.String
			}
		case videojob.FieldLocalInputName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field local_input_name", values[i])
			} else if value.Valid {
				_m.LocalInputName = new(string)
				*_m.LocalInputName = value.String
			}
		case videojob.FieldResult:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Result); err != nil {
					return fmt.Errorf("unmarshal field result: %w", err)
				}
			}
		case videojob.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case videojob.FieldHoldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field hold_amount", values[i])
			} else if value.Valid {
				_m.HoldAmount = new(float64)
				*_m.HoldAmount = value.Float64
			}
		case videojob.FieldActualCost:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field actual_cost", values[i])
			} else if value.Valid {
				_m.ActualCost = new(float64)
				*_m.ActualCost = value.Float64
			}
		case videojob.FieldBillingSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field billing_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BillingSnapshot); err != nil {
					return fmt.Errorf("unmarshal field billing_snapshot: %w", err)
				}
			}
		case videojob.FieldRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_hash", values[i])
			} else if value.Valid {
				_m.RequestHash = value.String
			}
		case videojob.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		case videojob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case videojob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case videojob.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case videojob.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VideoJob.
// This includes values selected through modifiers, order, etc.
func (_m *VideoJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this VideoJob.
// Note that you need to call VideoJob.Unwrap() before calling this method if this VideoJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VideoJob) Update() *VideoJobUpdateOne {
	return NewVideoJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VideoJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VideoJob) Unwrap() *VideoJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VideoJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VideoJob) String() string {
	var builder strings.Builder
	builder.WriteString("VideoJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("job_id=")
	builder.WriteString(_m.JobID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	if v := _m.UpstreamJobID; v != nil {
		builder.WriteString("upstream_job_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("requested_model=")
	builder.WriteString(_m.RequestedModel)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("prompt=")
	builder.WriteString(_m.Prompt)
	builder.WriteString(", ")
	builder.WriteString("resolution=")
	builder.WriteString(_m.Resolution)
	builder.WriteString(", ")
	builder.WriteString("duration_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationSeconds))
	builder.WriteString(", ")
	builder.WriteString("aspect_ratio=")
	builder.WriteString(_m.AspectRatio)
	builder.WriteString(", ")
	builder.WriteString("audio=")
	builder.WriteString(fmt.Sprintf("%v", _m.Audio))
	builder.WriteString(", ")
	builder.WriteString("image_source=")
	builder.WriteString(_m.ImageSource)
	builder.WriteString(", ")
	if v := _m.ImageURL; v != nil {
		builder.WriteString("image_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LocalInputName; v != nil {
		builder.WriteString("local_input_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(fmt.Sprintf("%v", _m.Result))
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.HoldAmount; v != nil {
		builder.WriteString("hold_amount=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActualCost; v != nil {
		builder.WriteString("actual_cost=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("billing_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.BillingSnapshot))
	builder.WriteString(", ")
	builder.WriteString("request_hash=")
	builder.WriteString(_m.RequestHash)
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// VideoJobs is a parsable slice of VideoJob.
type VideoJobs []*VideoJob
