// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/videojob"
)

// VideoJobCreate is the builder for creating a VideoJob entity.
type VideoJobCreate struct {
	config
	mutation *VideoJobMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetJobID sets the "job_id" field.
func (_c *VideoJobCreate) SetJobID(v string) *VideoJobCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *VideoJobCreate) SetUserID(v int64) *VideoJobCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *VideoJobCreate) SetAPIKeyID(v int64) *VideoJobCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *VideoJobCreate) SetGroupID(v int64) *VideoJobCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *VideoJobCreate) SetAccountID(v int64) *VideoJobCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetUpstreamJobID sets the "upstream_job_id" field.
func (_c *VideoJobCreate) SetUpstreamJobID(v int64) *VideoJobCreate {
	_c.mutation.SetUpstreamJobID(v)
	return _c
}

// SetNillableUpstreamJobID sets the "upstream_job_id" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableUpstreamJobID(v *int64) *VideoJobCreate {
	if v != nil {
		_c.SetUpstreamJobID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *VideoJobCreate) SetStatus(v string) *VideoJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetRequestedModel sets the "requested_model" field.
func (_c *VideoJobCreate) SetRequestedModel(v string) *VideoJobCreate {
	_c.mutation.SetRequestedModel(v)
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *VideoJobCreate) SetUpstreamModel(v string) *VideoJobCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetPrompt sets the "prompt" field.
func (_c *VideoJobCreate) SetPrompt(v string) *VideoJobCreate {
	_c.mutation.SetPrompt(v)
	return _c
}

// SetResolution sets the "resolution" field.
func (_c *VideoJobCreate) SetResolution(v string) *VideoJobCreate {
	_c.mutation.SetResolution(v)
	return _c
}

// SetDurationSeconds sets the "duration_seconds" field.
func (_c *VideoJobCreate) SetDurationSeconds(v int) *VideoJobCreate {
	_c.mutation.SetDurationSeconds(v)
	return _c
}

// SetAspectRatio sets the "aspect_ratio" field.
func (_c *VideoJobCreate) SetAspectRatio(v string) *VideoJobCreate {
	_c.mutation.SetAspectRatio(v)
	return _c
}

// SetAudio sets the "audio" field.
func (_c *VideoJobCreate) SetAudio(v bool) *VideoJobCreate {
	_c.mutation.SetAudio(v)
	return _c
}

// SetNillableAudio sets the "audio" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableAudio(v *bool) *VideoJobCreate {
	if v != nil {
		_c.SetAudio(*v)
	}
	return _c
}

// SetImageSource sets the "image_source" field.
func (_c *VideoJobCreate) SetImageSource(v string) *VideoJobCreate {
	_c.mutation.SetImageSource(v)
	return _c
}

// SetNillableImageSource sets the "image_source" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableImageSource(v *string) *VideoJobCreate {
	if v != nil {
		_c.SetImageSource(*v)
	}
	return _c
}

// SetImageURL sets the "image_url" field.
func (_c *VideoJobCreate) SetImageURL(v string) *VideoJobCreate {
	_c.mutation.SetImageURL(v)
	return _c
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableImageURL(v *string) *VideoJobCreate {
	if v != nil {
		_c.SetImageURL(*v)
	}
	return _c
}

// SetLocalInputName sets the "local_input_name" field.
func (_c *VideoJobCreate) SetLocalInputName(v string) *VideoJobCreate {
	_c.mutation.SetLocalInputName(v)
	return _c
}

// SetNillableLocalInputName sets the "local_input_name" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableLocalInputName(v *string) *VideoJobCreate {
	if v != nil {
		_c.SetLocalInputName(*v)
	}
	return _c
}

// SetResult sets the "result" field.
func (_c *VideoJobCreate) SetResult(v json.RawMessage) *VideoJobCreate {
	_c.mutation.SetResult(v)
	return _c
}

// SetErrorMessage sets the "error_message" field.
func (_c *VideoJobCreate) SetErrorMessage(v string) *VideoJobCreate {
	_c.mutation.SetErrorMessage(v)
	return _c
}

// SetNillableErrorMessage sets the "error_message" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableErrorMessage(v *string) *VideoJobCreate {
	if v != nil {
		_c.SetErrorMessage(*v)
	}
	return _c
}

// SetHoldAmount sets the "hold_amount" field.
func (_c *VideoJobCreate) SetHoldAmount(v float64) *VideoJobCreate {
	_c.mutation.SetHoldAmount(v)
	return _c
}

// SetNillableHoldAmount sets the "hold_amount" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableHoldAmount(v *float64) *VideoJobCreate {
	if v != nil {
		_c.SetHoldAmount(*v)
	}
	return _c
}

// SetActualCost sets the "actual_cost" field.
func (_c *VideoJobCreate) SetActualCost(v float64) *VideoJobCreate {
	_c.mutation.SetActualCost(v)
	return _c
}

// SetNillableActualCost sets the "actual_cost" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableActualCost(v *float64) *VideoJobCreate {
	if v != nil {
		_c.SetActualCost(*v)
	}
	return _c
}

// SetBillingSnapshot sets the "billing_snapshot" field.
func (_c *VideoJobCreate) SetBillingSnapshot(v json.RawMessage) *VideoJobCreate {
	_c.mutation.SetBillingSnapshot(v)
	return _c
}

// SetRequestHash sets the "request_hash" field.
func (_c *VideoJobCreate) SetRequestHash(v string) *VideoJobCreate {
	_c.mutation.SetRequestHash(v)
	return _c
}

// SetSettledAt sets the "settled_at" field.
func (_c *VideoJobCreate) SetSettledAt(v time.Time) *VideoJobCreate {
	_c.mutation.SetSettledAt(v)
	return _c
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableSettledAt(v *time.Time) *VideoJobCreate {
	if v != nil {
		_c.SetSettledAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VideoJobCreate) SetCreatedAt(v time.Time) *VideoJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableCreatedAt(v *time.Time) *VideoJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VideoJobCreate) SetUpdatedAt(v time.Time) *VideoJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableUpdatedAt(v *time.Time) *VideoJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *VideoJobCreate) SetStartedAt(v time.Time) *VideoJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableStartedAt(v *time.Time) *VideoJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *VideoJobCreate) SetFinishedAt(v time.Time) *VideoJobCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *VideoJobCreate) SetNillableFinishedAt(v *time.Time) *VideoJobCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// Mutation returns the VideoJobMutation object of the builder.
func (_c *VideoJobCreate) Mutation() *VideoJobMutation {
	return _c.mutation
}

// Save creates the VideoJob in the database.
func (_c *VideoJobCreate) Save(ctx context.Context) (*VideoJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VideoJobCreate) SaveX(ctx context.Context) *VideoJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VideoJobCreate) defaults() {
	if _, ok := _c.mutation.Audio(); !ok {
		v := videojob.DefaultAudio
		_c.mutation.SetAudio(v)
	}
	if _, ok := _c.mutation.ImageSource(); !ok {
		v := videojob.DefaultImageSource
		_c.mutation.SetImageSource(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := videojob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := videojob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VideoJobCreate) check() error {
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "VideoJob.job_id"`)}
	}
	if v, ok := _c.mutation.JobID(); ok {
		if err := videojob.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "VideoJob.job_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VideoJob.user_id"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "VideoJob.api_key_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "VideoJob.group_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "VideoJob.account_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "VideoJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := videojob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "VideoJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestedModel(); !ok {
		return &ValidationError{Name: "requested_model", err: errors.New(`ent: missing required field "VideoJob.requested_model"`)}
	}
	if v, ok := _c.mutation.RequestedModel(); ok {
		if err := videojob.RequestedModelValidator(v); err != nil {
			return &ValidationError{Name: "requested_model", err: fmt.Errorf(`ent: validator failed for field "VideoJob.requested_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "VideoJob.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := videojob.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "VideoJob.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Prompt(); !ok {
		return &ValidationError{Name: "prompt", err: errors.New(`ent: missing required field "VideoJob.prompt"`)}
	}
	if _, ok := _c.mutation.Resolution(); !ok {
		return &ValidationError{Name: "resolution", err: errors.New(`ent: missing required field "VideoJob.resolution"`)}
	}
	if v, ok := _c.mutation.Resolution(); ok {
		if err := videojob.ResolutionValidator(v); err != nil {
			return &ValidationError{Name: "resolution", err: fmt.Errorf(`ent: validator failed for field "VideoJob.resolution": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DurationSeconds(); !ok {
		return &ValidationError{Name: "duration_seconds", err: errors.New(`ent: missing required field "VideoJob.duration_seconds"`)}
	}
	if _, ok := _c.mutation.AspectRatio(); !ok {
		return &ValidationError{Name: "aspect_ratio", err: errors.New(`ent: missing required field "VideoJob.aspect_ratio"`)}
	}
	if v, ok := _c.mutation.AspectRatio(); ok {
		if err := videojob.AspectRatioValidator(v); err != nil {
			return &ValidationError{Name: "aspect_ratio", err: fmt.Errorf(`ent: validator failed for field "VideoJob.aspect_ratio": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Audio(); !ok {
		return &ValidationError{Name: "audio", err: errors.New(`ent: missing required field "VideoJob.audio"`)}
	}
	if _, ok := _c.mutation.ImageSource(); !ok {
		return &ValidationError{Name: "image_source", err: errors.New(`ent: missing required field "VideoJob.image_source"`)}
	}
	if v, ok := _c.mutation.ImageSource(); ok {
		if err := videojob.ImageSourceValidator(v); err != nil {
			return &ValidationError{Name: "image_source", err: fmt.Errorf(`ent: validator failed for field "VideoJob.image_source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LocalInputName(); ok {
		if err := videojob.LocalInputNameValidator(v); err != nil {
			return &ValidationError{Name: "local_input_name", err: fmt.Errorf(`ent: validator failed for field "VideoJob.local_input_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestHash(); !ok {
		return &ValidationError{Name: "request_hash", err: errors.New(`ent: missing required field "VideoJob.request_hash"`)}
	}
	if v, ok := _c.mutation.RequestHash(); ok {
		if err := videojob.RequestHashValidator(v); err != nil {
			return &ValidationError{Name: "request_hash", err: fmt.Errorf(`ent: validator failed for field "VideoJob.request_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VideoJob.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VideoJob.updated_at"`)}
	}
	return nil
}

func (_c *VideoJobCreate) sqlSave(ctx context.Context) (*VideoJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VideoJobCreate) createSpec() (*VideoJob, *sqlgraph.CreateSpec) {
	var (
		_node = &VideoJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(videojob.Table, sqlgraph.NewFieldSpec(videojob.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.JobID(); ok {
		_spec.SetField(videojob.FieldJobID, field.TypeString, value)
		_node.JobID = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(videojob.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(videojob.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(videojob.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(videojob.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.UpstreamJobID(); ok {
		_spec.SetField(videojob.FieldUpstreamJobID, field.TypeInt64, value)
		_node.UpstreamJobID = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(videojob.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RequestedModel(); ok {
		_spec.SetField(videojob.FieldRequestedModel, field.TypeString, value)
		_node.RequestedModel = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(videojob.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.Prompt(); ok {
		_spec.SetField(videojob.FieldPrompt, field.TypeString, value)
		_node.Prompt = value
	}
	if value, ok := _c.mutation.Resolution(); ok {
		_spec.SetField(videojob.FieldResolution, field.TypeString, value)
		_node.Resolution = value
	}
	if value, ok := _c.mutation.DurationSeconds(); ok {
		_spec.SetField(videojob.FieldDurationSeconds, field.TypeInt, value)
		_node.DurationSeconds = value
	}
	if value, ok := _c.mutation.AspectRatio(); ok {
		_spec.SetField(videojob.FieldAspectRatio, field.TypeString, value)
		_node.AspectRatio = value
	}
	if value, ok := _c.mutation.Audio(); ok {
		_spec.SetField(videojob.FieldAudio, field.TypeBool, value)
		_node.Audio = value
	}
	if value, ok := _c.mutation.ImageSource(); ok {
		_spec.SetField(videojob.FieldImageSource, field.TypeString, value)
		_node.ImageSource = value
	}
	if value, ok := _c.mutation.ImageURL(); ok {
		_spec.SetField(videojob.FieldImageURL, field.TypeString, value)
		_node.ImageURL = &value
	}
	if value, ok := _c.mutation.LocalInputName(); ok {
		_spec.SetField(videojob.FieldLocalInputName, field.TypeString, value)
		_node.LocalInputName = &value
	}
	if value, ok := _c.mutation.Result(); ok {
		_spec.SetField(videojob.FieldResult, field.TypeJSON, value)
		_node.Result = value
	}
	if value, ok := _c.mutation.ErrorMessage(); ok {
		_spec.SetField(videojob.FieldErrorMessage, field.TypeString, value)
		_node.ErrorMessage = &value
	}
	if value, ok := _c.mutation.HoldAmount(); ok {
		_spec.SetField(videojob.FieldHoldAmount, field.TypeFloat64, value)
		_node.HoldAmount = &value
	}
	if value, ok := _c.mutation.ActualCost(); ok {
		_spec.SetField(videojob.FieldActualCost, field.TypeFloat64, value)
		_node.ActualCost = &value
	}
	if value, ok := _c.mutation.BillingSnapshot(); ok {
		_spec.SetField(videojob.FieldBillingSnapshot, field.TypeJSON, value)
		_node.BillingSnapshot = value
	}
	if value, ok := _c.mutation.RequestHash(); ok {
		_spec.SetField(videojob.FieldRequestHash, field.TypeString, value)
		_node.RequestHash = value
	}
	if value, ok := _c.mutation.SettledAt(); ok {
		_spec.SetField(videojob.FieldSettledAt, field.TypeTime, value)
		_node.SettledAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(videojob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(videojob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(videojob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(videojob.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoJob.Create().
//		SetJobID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoJobUpsert) {
//			SetJobID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoJobCreate) OnConflict(opts ...sql.ConflictOption) *VideoJobUpsertOne {
	_c.conflict = opts
	return &VideoJobUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoJobCreate) OnConflictColumns(columns ...string) *VideoJobUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoJobUpsertOne{
		create: _c,
	}
}

type (
	// VideoJobUpsertOne is the builder for "upsert"-ing
	//  one VideoJob node.
	VideoJobUpsertOne struct {
		create *VideoJobCreate
	}

	// VideoJobUpsert is the "OnConflict" setter.
	VideoJobUpsert struct {
		*sql.UpdateSet
	}
)

// SetAccountID sets the "account_id" field.
func (u *VideoJobUpsert) SetAccountID(v int64) *VideoJobUpsert {
	u.Set(videojob.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateAccountID() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *VideoJobUpsert) AddAccountID(v int64) *VideoJobUpsert {
	u.Add(videojob.FieldAccountID, v)
	return u
}

// SetUpstreamJobID sets the "upstream_job_id" field.
func (u *VideoJobUpsert) SetUpstreamJobID(v int64) *VideoJobUpsert {
	u.Set(videojob.FieldUpstreamJobID, v)
	return u
}

// UpdateUpstreamJobID sets the "upstream_job_id" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateUpstreamJobID() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldUpstreamJobID)
	return u
}

// AddUpstreamJobID adds v to the "upstream_job_id" field.
func (u *VideoJobUpsert) AddUpstreamJobID(v int64) *VideoJobUpsert {
	u.Add(videojob.FieldUpstreamJobID, v)
	return u
}

// ClearUpstreamJobID clears the value of the "upstream_job_id" field.
func (u *VideoJobUpsert) ClearUpstreamJobID() *VideoJobUpsert {
	u.SetNull(videojob.FieldUpstreamJobID)
	return u
}

// SetStatus sets the "status" field.
func (u *VideoJobUpsert) SetStatus(v string) *VideoJobUpsert {
	u.Set(videojob.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateStatus() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldStatus)
	return u
}

// SetResult sets the "result" field.
func (u *VideoJobUpsert) SetResult(v json.RawMessage) *VideoJobUpsert {
	u.Set(videojob.FieldResult, v)
	return u
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateResult() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldResult)
	return u
}

// ClearResult clears the value of the "result" field.
func (u *VideoJobUpsert) ClearResult() *VideoJobUpsert {
	u.SetNull(videojob.FieldResult)
	return u
}

// SetErrorMessage sets the "error_message" field.
func (u *VideoJobUpsert) SetErrorMessage(v string) *VideoJobUpsert {
	u.Set(videojob.FieldErrorMessage, v)
	return u
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateErrorMessage() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldErrorMessage)
	return u
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *VideoJobUpsert) ClearErrorMessage() *VideoJobUpsert {
	u.SetNull(videojob.FieldErrorMessage)
	return u
}

// SetHoldAmount sets the "hold_amount" field.
func (u *VideoJobUpsert) SetHoldAmount(v float64) *VideoJobUpsert {
	u.Set(videojob.FieldHoldAmount, v)
	return u
}

// UpdateHoldAmount sets the "hold_amount" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateHoldAmount() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldHoldAmount)
	return u
}

// AddHoldAmount adds v to the "hold_amount" field.
func (u *VideoJobUpsert) AddHoldAmount(v float64) *VideoJobUpsert {
	u.Add(videojob.FieldHoldAmount, v)
	return u
}

// ClearHoldAmount clears the value of the "hold_amount" field.
func (u *VideoJobUpsert) ClearHoldAmount() *VideoJobUpsert {
	u.SetNull(videojob.FieldHoldAmount)
	return u
}

// SetActualCost sets the "actual_cost" field.
func (u *VideoJobUpsert) SetActualCost(v float64) *VideoJobUpsert {
	u.Set(videojob.FieldActualCost, v)
	return u
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateActualCost() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldActualCost)
	return u
}

// AddActualCost adds v to the "actual_cost" field.
func (u *VideoJobUpsert) AddActualCost(v float64) *VideoJobUpsert {
	u.Add(videojob.FieldActualCost, v)
	return u
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *VideoJobUpsert) ClearActualCost() *VideoJobUpsert {
	u.SetNull(videojob.FieldActualCost)
	return u
}

// SetSettledAt sets the "settled_at" field.
func (u *VideoJobUpsert) SetSettledAt(v time.Time) *VideoJobUpsert {
	u.Set(videojob.FieldSettledAt, v)
	return u
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateSettledAt() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldSettledAt)
	return u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *VideoJobUpsert) ClearSettledAt() *VideoJobUpsert {
	u.SetNull(videojob.FieldSettledAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoJobUpsert) SetUpdatedAt(v time.Time) *VideoJobUpsert {
	u.Set(videojob.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateUpdatedAt() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldUpdatedAt)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *VideoJobUpsert) SetStartedAt(v time.Time) *VideoJobUpsert {
	u.Set(videojob.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateStartedAt() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *VideoJobUpsert) ClearStartedAt() *VideoJobUpsert {
	u.SetNull(videojob.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *VideoJobUpsert) SetFinishedAt(v time.Time) *VideoJobUpsert {
	u.Set(videojob.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *VideoJobUpsert) UpdateFinishedAt() *VideoJobUpsert {
	u.SetExcluded(videojob.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *VideoJobUpsert) ClearFinishedAt() *VideoJobUpsert {
	u.SetNull(videojob.FieldFinishedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VideoJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoJobUpsertOne) UpdateNewValues() *VideoJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.JobID(); exists {
			s.SetIgnore(videojob.FieldJobID)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(videojob.FieldUserID)
		}
		if _, exists := u.create.mutation.APIKeyID(); exists {
			s.SetIgnore(videojob.FieldAPIKeyID)
		}
		if _, exists := u.create.mutation.GroupID(); exists {
			s.SetIgnore(videojob.FieldGroupID)
		}
		if _, exists := u.create.mutation.RequestedModel(); exists {
			s.SetIgnore(videojob.FieldRequestedModel)
		}
		if _, exists := u.create.mutation.UpstreamModel(); exists {
			s.SetIgnore(videojob.FieldUpstreamModel)
		}
		if _, exists := u.create.mutation.Prompt(); exists {
			s.SetIgnore(videojob.FieldPrompt)
		}
		if _, exists := u.create.mutation.Resolution(); exists {
			s.SetIgnore(videojob.FieldResolution)
		}
		if _, exists := u.create.mutation.DurationSeconds(); exists {
			s.SetIgnore(videojob.FieldDurationSeconds)
		}
		if _, exists := u.create.mutation.AspectRatio(); exists {
			s.SetIgnore(videojob.FieldAspectRatio)
		}
		if _, exists := u.create.mutation.Audio(); exists {
			s.SetIgnore(videojob.FieldAudio)
		}
		if _, exists := u.create.mutation.ImageSource(); exists {
			s.SetIgnore(videojob.FieldImageSource)
		}
		if _, exists := u.create.mutation.ImageURL(); exists {
			s.SetIgnore(videojob.FieldImageURL)
		}
		if _, exists := u.create.mutation.LocalInputName(); exists {
			s.SetIgnore(videojob.FieldLocalInputName)
		}
		if _, exists := u.create.mutation.BillingSnapshot(); exists {
			s.SetIgnore(videojob.FieldBillingSnapshot)
		}
		if _, exists := u.create.mutation.RequestHash(); exists {
			s.SetIgnore(videojob.FieldRequestHash)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(videojob.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoJob.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VideoJobUpsertOne) Ignore() *VideoJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoJobUpsertOne) DoNothing() *VideoJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoJobCreate.OnConflict
// documentation for more info.
func (u *VideoJobUpsertOne) Update(set func(*VideoJobUpsert)) *VideoJobUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *VideoJobUpsertOne) SetAccountID(v int64) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *VideoJobUpsertOne) AddAccountID(v int64) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateAccountID() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateAccountID()
	})
}

// SetUpstreamJobID sets the "upstream_job_id" field.
func (u *VideoJobUpsertOne) SetUpstreamJobID(v int64) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetUpstreamJobID(v)
	})
}

// AddUpstreamJobID adds v to the "upstream_job_id" field.
func (u *VideoJobUpsertOne) AddUpstreamJobID(v int64) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.AddUpstreamJobID(v)
	})
}

// UpdateUpstreamJobID sets the "upstream_job_id" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateUpstreamJobID() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateUpstreamJobID()
	})
}

// ClearUpstreamJobID clears the value of the "upstream_job_id" field.
func (u *VideoJobUpsertOne) ClearUpstreamJobID() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearUpstreamJobID()
	})
}

// SetStatus sets the "status" field.
func (u *VideoJobUpsertOne) SetStatus(v string) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateStatus() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateStatus()
	})
}

// SetResult sets the "result" field.
func (u *VideoJobUpsertOne) SetResult(v json.RawMessage) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateResult() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateResult()
	})
}

// ClearResult clears the value of the "result" field.
func (u *VideoJobUpsertOne) ClearResult() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearResult()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *VideoJobUpsertOne) SetErrorMessage(v string) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateErrorMessage() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *VideoJobUpsertOne) ClearErrorMessage() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearErrorMessage()
	})
}

// SetHoldAmount sets the "hold_amount" field.
func (u *VideoJobUpsertOne) SetHoldAmount(v float64) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetHoldAmount(v)
	})
}

// AddHoldAmount adds v to the "hold_amount" field.
func (u *VideoJobUpsertOne) AddHoldAmount(v float64) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.AddHoldAmount(v)
	})
}

// UpdateHoldAmount sets the "hold_amount" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateHoldAmount() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateHoldAmount()
	})
}

// ClearHoldAmount clears the value of the "hold_amount" field.
func (u *VideoJobUpsertOne) ClearHoldAmount() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearHoldAmount()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *VideoJobUpsertOne) SetActualCost(v float64) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *VideoJobUpsertOne) AddActualCost(v float64) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateActualCost() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateActualCost()
	})
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *VideoJobUpsertOne) ClearActualCost() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearActualCost()
	})
}

// SetSettledAt sets the "settled_at" field.
func (u *VideoJobUpsertOne) SetSettledAt(v time.Time) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetSettledAt(v)
	})
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateSettledAt() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateSettledAt()
	})
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *VideoJobUpsertOne) ClearSettledAt() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearSettledAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoJobUpsertOne) SetUpdatedAt(v time.Time) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateUpdatedAt() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *VideoJobUpsertOne) SetStartedAt(v time.Time) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateStartedAt() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *VideoJobUpsertOne) ClearStartedAt() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *VideoJobUpsertOne) SetFinishedAt(v time.Time) *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *VideoJobUpsertOne) UpdateFinishedAt() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *VideoJobUpsertOne) ClearFinishedAt() *VideoJobUpsertOne {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *VideoJobUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoJobCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoJobUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VideoJobUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VideoJobUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VideoJobCreateBulk is the builder for creating many VideoJob entities in bulk.
type VideoJobCreateBulk struct {
	config
	err      error
	builders []*VideoJobCreate
	conflict []sql.ConflictOption
}

// Save creates the VideoJob entities in the database.
func (_c *VideoJobCreateBulk) Save(ctx context.Context) ([]*VideoJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VideoJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VideoJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VideoJobCreateBulk) SaveX(ctx context.Context) []*VideoJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VideoJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VideoJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VideoJob.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VideoJobUpsert) {
//			SetJobID(v+v).
//		}).
//		Exec(ctx)
func (_c *VideoJobCreateBulk) OnConflict(opts ...sql.ConflictOption) *VideoJobUpsertBulk {
	_c.conflict = opts
	return &VideoJobUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VideoJob.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VideoJobCreateBulk) OnConflictColumns(columns ...string) *VideoJobUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VideoJobUpsertBulk{
		create: _c,
	}
}

// VideoJobUpsertBulk is the builder for "upsert"-ing
// a bulk of VideoJob nodes.
type VideoJobUpsertBulk struct {
	create *VideoJobCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VideoJob.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VideoJobUpsertBulk) UpdateNewValues() *VideoJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.JobID(); exists {
				s.SetIgnore(videojob.FieldJobID)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(videojob.FieldUserID)
			}
			if _, exists := b.mutation.APIKeyID(); exists {
				s.SetIgnore(videojob.FieldAPIKeyID)
			}
			if _, exists := b.mutation.GroupID(); exists {
				s.SetIgnore(videojob.FieldGroupID)
			}
			if _, exists := b.mutation.RequestedModel(); exists {
				s.SetIgnore(videojob.FieldRequestedModel)
			}
			if _, exists := b.mutation.UpstreamModel(); exists {
				s.SetIgnore(videojob.FieldUpstreamModel)
			}
			if _, exists := b.mutation.Prompt(); exists {
				s.SetIgnore(videojob.FieldPrompt)
			}
			if _, exists := b.mutation.Resolution(); exists {
				s.SetIgnore(videojob.FieldResolution)
			}
			if _, exists := b.mutation.DurationSeconds(); exists {
				s.SetIgnore(videojob.FieldDurationSeconds)
			}
			if _, exists := b.mutation.AspectRatio(); exists {
				s.SetIgnore(videojob.FieldAspectRatio)
			}
			if _, exists := b.mutation.Audio(); exists {
				s.SetIgnore(videojob.FieldAudio)
			}
			if _, exists := b.mutation.ImageSource(); exists {
				s.SetIgnore(videojob.FieldImageSource)
			}
			if _, exists := b.mutation.ImageURL(); exists {
				s.SetIgnore(videojob.FieldImageURL)
			}
			if _, exists := b.mutation.LocalInputName(); exists {
				s.SetIgnore(videojob.FieldLocalInputName)
			}
			if _, exists := b.mutation.BillingSnapshot(); exists {
				s.SetIgnore(videojob.FieldBillingSnapshot)
			}
			if _, exists := b.mutation.RequestHash(); exists {
				s.SetIgnore(videojob.FieldRequestHash)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(videojob.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VideoJob.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VideoJobUpsertBulk) Ignore() *VideoJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VideoJobUpsertBulk) DoNothing() *VideoJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VideoJobCreateBulk.OnConflict
// documentation for more info.
func (u *VideoJobUpsertBulk) Update(set func(*VideoJobUpsert)) *VideoJobUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VideoJobUpsert{UpdateSet: update})
	}))
	return u
}

// SetAccountID sets the "account_id" field.
func (u *VideoJobUpsertBulk) SetAccountID(v int64) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *VideoJobUpsertBulk) AddAccountID(v int64) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateAccountID() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateAccountID()
	})
}

// SetUpstreamJobID sets the "upstream_job_id" field.
func (u *VideoJobUpsertBulk) SetUpstreamJobID(v int64) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetUpstreamJobID(v)
	})
}

// AddUpstreamJobID adds v to the "upstream_job_id" field.
func (u *VideoJobUpsertBulk) AddUpstreamJobID(v int64) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.AddUpstreamJobID(v)
	})
}

// UpdateUpstreamJobID sets the "upstream_job_id" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateUpstreamJobID() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateUpstreamJobID()
	})
}

// ClearUpstreamJobID clears the value of the "upstream_job_id" field.
func (u *VideoJobUpsertBulk) ClearUpstreamJobID() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearUpstreamJobID()
	})
}

// SetStatus sets the "status" field.
func (u *VideoJobUpsertBulk) SetStatus(v string) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateStatus() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateStatus()
	})
}

// SetResult sets the "result" field.
func (u *VideoJobUpsertBulk) SetResult(v json.RawMessage) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetResult(v)
	})
}

// UpdateResult sets the "result" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateResult() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateResult()
	})
}

// ClearResult clears the value of the "result" field.
func (u *VideoJobUpsertBulk) ClearResult() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearResult()
	})
}

// SetErrorMessage sets the "error_message" field.
func (u *VideoJobUpsertBulk) SetErrorMessage(v string) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetErrorMessage(v)
	})
}

// UpdateErrorMessage sets the "error_message" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateErrorMessage() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateErrorMessage()
	})
}

// ClearErrorMessage clears the value of the "error_message" field.
func (u *VideoJobUpsertBulk) ClearErrorMessage() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearErrorMessage()
	})
}

// SetHoldAmount sets the "hold_amount" field.
func (u *VideoJobUpsertBulk) SetHoldAmount(v float64) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetHoldAmount(v)
	})
}

// AddHoldAmount adds v to the "hold_amount" field.
func (u *VideoJobUpsertBulk) AddHoldAmount(v float64) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.AddHoldAmount(v)
	})
}

// UpdateHoldAmount sets the "hold_amount" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateHoldAmount() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateHoldAmount()
	})
}

// ClearHoldAmount clears the value of the "hold_amount" field.
func (u *VideoJobUpsertBulk) ClearHoldAmount() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearHoldAmount()
	})
}

// SetActualCost sets the "actual_cost" field.
func (u *VideoJobUpsertBulk) SetActualCost(v float64) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetActualCost(v)
	})
}

// AddActualCost adds v to the "actual_cost" field.
func (u *VideoJobUpsertBulk) AddActualCost(v float64) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.AddActualCost(v)
	})
}

// UpdateActualCost sets the "actual_cost" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateActualCost() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateActualCost()
	})
}

// ClearActualCost clears the value of the "actual_cost" field.
func (u *VideoJobUpsertBulk) ClearActualCost() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearActualCost()
	})
}

// SetSettledAt sets the "settled_at" field.
func (u *VideoJobUpsertBulk) SetSettledAt(v time.Time) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetSettledAt(v)
	})
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateSettledAt() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateSettledAt()
	})
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *VideoJobUpsertBulk) ClearSettledAt() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearSettledAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VideoJobUpsertBulk) SetUpdatedAt(v time.Time) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateUpdatedAt() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *VideoJobUpsertBulk) SetStartedAt(v time.Time) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateStartedAt() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *VideoJobUpsertBulk) ClearStartedAt() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *VideoJobUpsertBulk) SetFinishedAt(v time.Time) *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *VideoJobUpsertBulk) UpdateFinishedAt() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *VideoJobUpsertBulk) ClearFinishedAt() *VideoJobUpsertBulk {
	return u.Update(func(s *VideoJobUpsert) {
		s.ClearFinishedAt()
	})
}

// Exec executes the query.
func (u *VideoJobUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VideoJobCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VideoJobCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VideoJobUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
